[package]
name = "browser-window-ffi"
version = "0.0.0"
description = "FFI bindings for the browser-window create."
edition = "2018"
authors = ["Danny de Jong"]
license = "MIT"
publish = true
categories = ["external-ffi-bindings"]
repository = "https://github.com/bamilab/browser-window"

[lib]
name = "browser_window_ffi"
path = "src/lib.rs"
crate-type = ["rlib"]

[build-dependencies]
cc = "1.0"
