[package]
name = "browser-window-example"
version = "0.0.0"
description = "A simple example that demonstrates how you can use browser windows asynchronously."
edition = "2018"
publish = false

[dependencies]
browser-window = { path = ".." }
serde_json = "1.0"
