[package]
name = "browser-window"
version = "0.5.7"
description = "A simple async/await aware browser (GUI) toolkit."
edition = "2018"
authors = ["Danny de Jong"]
license = "MIT"
publish = true
keywords = ["browser", "chromium", "electron", "gui", "webview"]
categories = ["asynchronous", "gui", "web-programming"]
readme = "README.md"
repository = "https://github.com/bamilab/browser-window"
documentation = "https://bamilab.github.io/browser-window/browser_window/"

[features]
default = ["cef"]
cef = ["browser-window-core/cef"]
gtk = ["browser-window-core/gtk"]
threadsafe = []

[lib]
name = "browser_window"
path = "src/lib.rs"

[[example]]
name = "terminal"
path = "examples/terminal.rs"

[dependencies]
browser-window-core = { path = "./core", version = "0.0.4", features = [ "cef" ] }
futures-channel = { version = "^0.3" }
lazy_static = "1"
unsafe-send-sync = "^0.1"

[dev-dependencies]
serde_json = "^1.0"

[package.metadata.docs.rs]
all-features = true

[workspace]
members = ["c", "core"]