[package]
name = "browser-window"
version = "0.2.3"
description = "An async/await aware browser (GUI) toolkit like Electron."
edition = "2018"
authors = ["Danny de Jong"]
license = "MIT"
publish = true
keywords = ["browser", "chromium", "electron", "gui", "webview"]
categories = ["asynchronous", "gui", "web-programming"]
readme = "README.md"
repository = "https://github.com/bamilab/browser-window"

[features]
edge = ["browser-window-ffi/edge"]

[lib]
name = "browser_window"
path = "src/lib.rs"

[dependencies]
boxfnonce = "0.1"
browser-window-ffi = { path = "./ffi", version = "0.2.3" }
futures-channel = { version = "0.3" }

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-pc-windows-msvc"
