[package]
name = "browser-window"
version = "0.5.1"
description = "A simple async/await aware browser (GUI) toolkit."
edition = "2018"
authors = ["Danny de Jong"]
license = "MIT"
publish = true
keywords = ["browser", "chromium", "electron", "gui", "webview"]
categories = ["asynchronous", "gui", "web-programming"]
readme = "README.md"
repository = "https://github.com/bamilab/browser-window"

[features]
default = ["cef"]
cef = ["browser-window-core/cef"]
gtk = ["browser-window-core/gtk"]
threadsafe = []

[lib]
name = "browser_window"
path = "src/lib.rs"

[dependencies]
browser-window-core = { path = "./core", version = "0.0.1", features = [ "cef" ] }
futures-channel = { version = "^0.3" }
lazy_static = "1"
unsafe-send-sync = "^0.1"

[dev-dependencies]
tokio = { version = "^0.3", features = [ "rt-multi-thread" ] }

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-pc-windows-msvc"

[workspace]
members = ["c", "core", "example"]