[package]
name = "browser-window"
version = "0.4.1"
description = "A simple async/await aware browser (GUI) toolkit."
edition = "2018"
authors = ["Danny de Jong"]
license = "MIT"
publish = true
keywords = ["browser", "chromium", "electron", "gui", "webview"]
categories = ["asynchronous", "gui", "web-programming"]
readme = "README.md"
repository = "https://github.com/bamilab/browser-window"

[features]
cef = ["browser-window-c/cef"]
gtk = ["browser-window-c/gtk"]
threadsafe = []

[lib]
name = "browser_window"
path = "src/lib.rs"

[dependencies]
browser-window-c = { path = "./c" }
browser-window-core = { path = "./core" }
futures-channel = { version = "^0.3" }
lazy_static = "1"
unsafe-send-sync = "0"

[dev-dependencies]
tokio = { version = "^0.3", features = [ "rt-multi-thread" ] }

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-pc-windows-msvc"
